name: arosa_je
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.0-186.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_localization: ^0.2.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.0
  intl: ^0.18.1
  gap: ^3.0.1
  get: ^4.6.6
  latlong2: ^0.9.0
  url_launcher: ^6.2.2
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7


flutter:

  uses-material-design: true
  generate: true
  assets:
    - lib/assets/images/
